#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("timesheet.Resource", IsApplication=true)]

namespace timesheet
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050015
			public const int button1 = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int button3 = 2131034134;
			
			// aapt resource value: 0x7f050001
			public const int label2 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int label3 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int label4 = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int label5 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int label6 = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int label7 = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int show1 = 2131034112;
			
			// aapt resource value: 0x7f05000f
			public const int show10 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int show11 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int show12 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int show13 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int show14 = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int show15 = 2131034132;
			
			// aapt resource value: 0x7f050004
			public const int show2 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int show3 = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int show4 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int show5 = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int show6 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int show7 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int show8 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int show9 = 2131034126;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int empty = 2130968578;
			
			// aapt resource value: 0x7f04000e
			public const int fifth = 2130968590;
			
			// aapt resource value: 0x7f04000a
			public const int first = 2130968586;
			
			// aapt resource value: 0x7f04000d
			public const int fourth = 2130968589;
			
			// aapt resource value: 0x7f040001
			public const int initalizing = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int label1 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int label2 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int label3 = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int label4 = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int label5 = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int label6 = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int label7 = 2130968585;
			
			// aapt resource value: 0x7f04000f
			public const int left = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int right = 2130968592;
			
			// aapt resource value: 0x7f04000b
			public const int second = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int third = 2130968588;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
